name: "convnext_classifier"
platform: "onnxruntime_onnx"
max_batch_size: 8

input [
  {
    name: "pixel_values"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  }
]

output [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [ 100 ]
  }
]